---
title: 'ESM 204 #4'
author: "Sage Kime and Karla Garibay Garcia"
date: "5/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
options(scipen = 0)
```


### 1. Quadratic Damage Function 

```{r}
# Read in data
warming <- read.csv("warming.csv")
damages <- read.csv("damages.csv")

#create new variable for warming^2 (followed tutorial from statology.org/quadratic-regression-r/)
damages$warming2 <- damages$warming^2

#fit quadratic regression model
quadmodel <- lm(damages ~ warming + warming2 -1, data=damages)

summary(quadmodel)

# damages = -1.035e12x + 1.94e13x^2

warming_values <- seq(0,10,0.1)

#create list of predicted warming levels using quadratic model
predicted_damages <- predict(quadmodel, list(warming=warming_values, warming2=warming_values^2))

#plot with quad regression 
plot(damages$warming, damages$damages) +
  lines(warming_values, predicted_damages, col='blue')

#exploratory ggplot
ggplot(data = damages, aes(x = warming, y = damages)) +
  geom_point(alpha = .5,
              width = 1.5,
              size = 2,
              color = "darkred",
              ) +
    labs(y = "Financial Damages ($)", title = "Estimated annual total damages from climate change based on warming", x = "Degrees of Warming (C)") +
    theme_minimal() 

```

### 2. Damages in each year under the baseline climate and pulse scenarios

```{r}
#Damages WITHOUT pulse

# Name coefficients
a <- quadmodel$coefficients[[1]]
b <- quadmodel$coefficients[[2]]

#create function
base_damage <- function(x, quadmodel) {
  baseline_damage <- quadmodel$coefficients[[1]]*x + quadmodel$coefficients[[2]]*x^2
  return(baseline_damage)
}

#test fuction - create vector
base_damage(warming$warming_baseline, quadmodel)

#convert vector to variable in warming dataset
warming$damages_baseline <- base_damage(warming$warming_baseline, quadmodel)


#Damages WITH pulse

#create function
pul_damage <- function(x, quadmodel) {
  pulse_damage <- quadmodel$coefficients[[1]]*x + quadmodel$coefficients[[2]]*x^2
  return(pulse_damage)
}

#test fuction - create vector
pul_damage(warming$warming_pulse, quadmodel)

#convert vector to variable in warming dataset
warming$damages_pulse <- pul_damage(warming$warming_pulse, quadmodel)


```

